#!/usr/bin/env bash
set -e

# Usage: ./ralph.sh <name> [plan|build] [max_iterations] [--spec <path>]
# Examples:
#   ./ralph.sh game plan 5 --spec docs/plans/my-plan.md   # First run: link spec, then plan
#   ./ralph.sh game plan 5     # Planning mode, 5 iterations
#   ./ralph.sh game build 50   # Building mode, 50 iterations
#   ./ralph.sh game 50         # Building mode (default), 50 iterations
#   ./ralph.sh game plan       # Planning mode, unlimited
#   ./ralph.sh game             # Building mode, unlimited
#
# Files used/created per workstream:
#   docs/ralph/<name>-spec.md      # Your requirements (symlinked or authored by you)
#   docs/ralph/<name>-plan.md      # Planning mode prompt (auto-generated, editable)
#   docs/ralph/<name>-build.md     # Building mode prompt (auto-generated, editable)
#   docs/ralph/<name>-impl.md      # Implementation plan (generated by Ralph)
#   docs/ralph/<name>-tests.json   # Test manifest (maintained by Ralph)
#   docs/ralph/<name>-progress.txt # Progress log (maintained by Ralph)
#   docs/ralph/AGENTS.md           # Operational guide (shared, maintained by Ralph)

if [ -z "$1" ]; then
  echo "Usage: $0 <name> [plan|build] [max_iterations] [--spec <path>]"
  echo ""
  echo "Examples:"
  echo "  $0 game plan 5 --spec docs/plans/my-plan.md"
  echo "  $0 game plan 5"
  echo "  $0 game build 50"
  echo "  $0 game 50"
  exit 1
fi

NAME="$1"
shift

# Parse mode, iterations, and --spec flag
MODE="build"
MAX_ITERATIONS=0
SPEC_SOURCE=""

while [ $# -gt 0 ]; do
  case "$1" in
    plan|build)
      MODE="$1"
      shift
      ;;
    --spec)
      SPEC_SOURCE="$2"
      shift 2
      ;;
    *)
      if [[ "$1" =~ ^[0-9]+$ ]]; then
        MAX_ITERATIONS="$1"
      fi
      shift
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WEB_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$WEB_DIR"

RALPH_DIR="docs/ralph"
SPEC="${RALPH_DIR}/${NAME}-spec.md"
PLAN_PROMPT="${RALPH_DIR}/${NAME}-plan.md"
BUILD_PROMPT="${RALPH_DIR}/${NAME}-build.md"
IMPL="${RALPH_DIR}/${NAME}-impl.md"
TESTS="${RALPH_DIR}/${NAME}-tests.json"
PROGRESS="${RALPH_DIR}/${NAME}-progress.txt"
AGENTS="${RALPH_DIR}/AGENTS.md"

# Select prompt file based on mode
if [ "$MODE" = "plan" ]; then
  PROMPT_FILE="$PLAN_PROMPT"
else
  PROMPT_FILE="$BUILD_PROMPT"
fi

# --- Link or verify spec ---
if [ -n "$SPEC_SOURCE" ]; then
  if [ ! -f "$SPEC_SOURCE" ]; then
    echo "ERROR: Spec source not found at $SPEC_SOURCE"
    exit 1
  fi
  # Create relative symlink from ralph dir to spec source
  SPEC_ABS="$(cd "$(dirname "$SPEC_SOURCE")" && pwd)/$(basename "$SPEC_SOURCE")"
  ln -sf "$SPEC_ABS" "$SPEC"
  echo "Linked $SPEC -> $SPEC_ABS"
fi

if [ ! -f "$SPEC" ]; then
  echo "ERROR: Spec not found at $SPEC"
  echo ""
  echo "Either create $SPEC directly, or link an existing file:"
  echo "  $0 $NAME plan 3 --spec docs/plans/your-plan.md"
  exit 1
fi

# --- Auto-generate prompt files if missing ---
if [ ! -f "$PLAN_PROMPT" ]; then
  cat > "$PLAN_PROMPT" << EOF
0a. Study @${SPEC} to learn the application specifications and requirements.
0b. Study @${IMPL} (if present) to understand the plan so far.
0c. Study @${AGENTS} for build/test commands and codebase patterns.
0d. For reference, the application source code is in \`src/\`.

1. Study @${IMPL} (if present; it may be incorrect) and compare existing source code in \`src/\` against @${SPEC}. Create/update @${IMPL} as a prioritized bullet list of items yet to be implemented. Don't assume functionality is missing — confirm with code search first. Consider searching for TODO, minimal implementations, placeholders, skipped tests, and inconsistent patterns.

IMPORTANT: Plan only. Do NOT implement anything.

99999. Keep @${IMPL} current — future iterations depend on this to avoid duplicating efforts.
999999. If you find inconsistencies in @${SPEC}, note them in @${IMPL} rather than modifying the spec.
9999999. When @${IMPL} becomes large, clean out completed items.
EOF
  echo "Created $PLAN_PROMPT"
fi

if [ ! -f "$BUILD_PROMPT" ]; then
  cat > "$BUILD_PROMPT" << EOF
0a. Study @${SPEC} to learn the application specifications and requirements.
0b. Study @${IMPL}.
0c. Study @${AGENTS} for build/test commands and codebase patterns.

1. Your task is to implement functionality per the specifications. Follow @${IMPL} and choose the most important item to address. Before making changes, search the codebase — don't assume not implemented. Implement functionality completely — no placeholders or stubs.
2. After implementing, run the validation commands from @${AGENTS}. If tests are missing for the functionality you implemented, write them. Update @${TESTS} with any new or updated tests.
3. When you discover issues, immediately update @${IMPL} with your findings. When resolved, update and remove the item.
4. When checks pass, update @${IMPL}, then git commit with a message describing the changes.

99999. Important: When authoring tests or documentation, capture the why.
999999. Important: It is unacceptable to remove or weaken existing tests. Fix the code, not the tests. You may add NEW tests.
9999999. Keep @${IMPL} current with learnings — future iterations depend on this to avoid duplicating efforts. Update especially after finishing your turn.
99999999. When you learn something new about how to build or run the project, update @${AGENTS} but keep it brief and operational only.
999999999. For any bugs you notice, resolve them or document them in @${IMPL} even if unrelated to current work.
9999999999. Implement functionality completely. Placeholders and stubs waste effort and time redoing the same work.
99999999999. When @${IMPL} becomes large, clean out completed items.
999999999999. Append a brief progress note to @${PROGRESS} after committing.
EOF
  echo "Created $BUILD_PROMPT"
fi

# --- Auto-create state files if missing ---
if [ ! -f "$IMPL" ]; then
  echo "<!-- Generated and maintained by Ralph. Prioritized list of items to implement. -->" > "$IMPL"
  echo "Created $IMPL"
fi

if [ ! -f "$TESTS" ]; then
  cat > "$TESTS" << EOFTEST
{
  "description": "Test manifest for '${NAME}'. Tracks all tests, their status, and what they cover.",
  "rules": [
    "Never remove or weaken existing tests — only add or fix them.",
    "Update status after running: not_started -> failing -> passing.",
    "Add new entries when writing new test files or test cases."
  ],
  "tests": []
}
EOFTEST
  echo "Created $TESTS"
fi

if [ ! -f "$PROGRESS" ]; then
  cat > "$PROGRESS" << 'EOFPROG'
# Progress Log
# Each iteration appends its progress here.
# ---
EOFPROG
  echo "Created $PROGRESS"
fi

# --- Verify prompt file exists ---
if [ ! -f "$PROMPT_FILE" ]; then
  echo "ERROR: Prompt file not found at $PROMPT_FILE"
  exit 1
fi

# --- Run init ---
bash "${RALPH_DIR}/init.sh" "$NAME"

CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
ITERATION=0

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Ralph: $NAME"
echo "  Mode:   $MODE"
echo "  Prompt: $PROMPT_FILE"
echo "  Branch: $CURRENT_BRANCH"
[ "$MAX_ITERATIONS" -gt 0 ] && echo "  Max:    $MAX_ITERATIONS iterations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

while true; do
  if [ "$MAX_ITERATIONS" -gt 0 ] && [ "$ITERATION" -ge "$MAX_ITERATIONS" ]; then
    echo "Reached max iterations: $MAX_ITERATIONS"
    break
  fi

  ITERATION=$((ITERATION + 1))
  echo ""
  echo "==============================="
  echo "  [$NAME:$MODE] Iteration $ITERATION"
  echo "==============================="

  cat "$PROMPT_FILE" | claude -p \
    --dangerously-skip-permissions \
    --model opus \
    --verbose

  echo ""
  echo "======================== [$NAME:$MODE] Iteration $ITERATION complete ========================"
done
